# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGW_k5DI5uHeXG5zP3Pqkk9XWjc8H0RY
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer, util
from transformers import pipeline


# =========================================================
#                 PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="Owl Movement Classifier",
    page_icon="🦉",
    layout="wide"
)

# Title
st.title("🦉 Owl Movement Classifier — RAG + SHAP + LLM")
st.write("This Streamlit app integrates a RandomForest classifier, SHAP explainability, a RAG retriever, and FLAN-T5 LLM for ecological explanations.")



# =========================================================
#                 LOAD CLASSIFIER
# =========================================================
@st.cache_resource
def load_model():
    return joblib.load("owl_rf_binary.pkl")

rf_model = load_model()


# =========================================================
#                 FEATURE LIST
# =========================================================
feature_cols = [
    'snr','sig','sigsd','noise',
    'sig_lag1','sig_lag2',
    'snr_lag1','snr_lag2',
    'sig_roll3','sig_roll5',
    'time_diff','detections_cum',
    'sig_diff','noise_spike',
    'weak_signal','strong_signal'
]


# =========================================================
#                 LOAD DATASET
# =========================================================
st.sidebar.header("📂 Upload Dataset")
uploaded = st.sidebar.file_uploader("Upload df_fe_sample.csv", type=["csv"])

if uploaded:
    df = pd.read_csv(uploaded)
    st.sidebar.success("Dataset loaded successfully!")
else:
    st.warning("Upload df_fe_sample.csv to continue.")
    st.stop()


# =========================================================
#                 SHAP EXPLAINER
# =========================================================
@st.cache_resource
def build_shap_explainer():
    return shap.TreeExplainer(rf_model)

explainer = build_shap_explainer()


def shap_for_row(row):
    """SHAP values for class=1 (migratory/vagrant)."""
    X = row[feature_cols].values.reshape(1, -1)
    vals = explainer.shap_values(X)[1][0]   # class 1
    return vals


def shap_text_summary(row, shap_vals):
    """Generate top 5 SHAP textual explanation."""
    pairs = list(zip(feature_cols, shap_vals))
    pairs_sorted = sorted(pairs, key=lambda x: abs(x[1]), reverse=True)[:5]

    explanation = "Top SHAP feature contributions:\n"
    for feat, val in pairs_sorted:
        direction = "increases migration likelihood" if val > 0 else "supports residency"
        explanation += f"- {feat}: {val:.3f} → {direction}\n"
    return explanation



# =========================================================
#                 RAG RETRIEVER
# =========================================================
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Documents for retrieval
rag_docs = {
    "model_info": """
    The owl movement classifier predicts Resident vs Migratory/Vagrant behavior.
    A long time_diff indicates the owl was absent for 24 hours or more.
    Continuous detections usually indicate residency.
    """,
    "feature_info": """
    SHAP values show which MOTUS features contributed to the prediction.
    time_diff, snr_lag1, sig_lag2, and rolling features are often important.
    """
}

rag_embeddings = {
    k: embedder.encode(v, convert_to_tensor=True)
    for k, v in rag_docs.items()
}


def retrieve_context(query):
    q = embedder.encode(query, convert_to_tensor=True)
    scores = {k: util.cos_sim(q, emb).item() for k, emb in rag_embeddings.items()}
    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return "\n\n".join([rag_docs[k] for k, _ in ranked[:2]])



# =========================================================
#                 FLAN-T5 LLM
# =========================================================
@st.cache_resource
def load_llm():
    return pipeline("text2text-generation", model="google/flan-t5-large")

generator = load_llm()



def llm_explain(row, shap_text, rag_text):
    prompt = f"""
You are an owl movement ecologist.

DATA ROW:
{row.to_string()}

SHAP SUMMARY:
{shap_text}

RAG KNOWLEDGE:
{rag_text}

Explain the movement behavior (Resident vs Migratory/Vagrant)
using ecological reasoning.
"""

    out = generator(prompt, max_new_tokens=200, temperature=0.5)[0]["generated_text"]
    return out



# =========================================================
#                 SIDEBAR NAVIGATION
# =========================================================
page = st.sidebar.radio(
    "Navigation",
    ["🏠 Home", "🔍 Prediction Explorer", "📈 SHAP Explainability", "🧠 RAG Movement Explanation", "💬 Owl Chatbot", "📘 Documentation"]
)



# =========================================================
#                 PAGE 1 — HOME
# =========================================================
if page == "🏠 Home":
    st.header("Welcome to the Owl Movement Prediction System")
    st.write("""
    This tool predicts owl movement types (Resident vs Migratory/Vagrant)
    using MOTUS receiver detection features.

    ### Included:
    - RandomForest classifier
    - SHAP explainability (local + global)
    - RAG retriever
    - FLAN-T5 natural language reasoning
    - Multi-page Streamlit UI
    """)



# =========================================================
#      PAGE 2 — PREDICTION + SHAP LOCAL EXPLAINABILITY
# =========================================================
elif page == "🔍 Prediction Explorer":

    st.header("🔍 Prediction Explorer")

    idx = st.number_input("Select row index:", min_value=0, max_value=len(df)-1, value=0)

    row = df.iloc[idx]
    X = row[feature_cols].values.reshape(1, -1)

    pred = rf_model.predict(X)[0]
    prob = rf_model.predict_proba(X).max()

    label = {0: "Resident", 1: "Migratory/Vagrant"}[pred]

    st.subheader("Model Prediction")
    st.write(f"**Prediction:** {label}")
    st.write(f"**Confidence:** {prob:.2f}")

    # SHAP Summary
    shap_vals = shap_for_row(row)
    shap_text = shap_text_summary(row, shap_vals)

    st.subheader("SHAP Local Explanation (Text)")
    st.text(shap_text)

    # Waterfall
    st.subheader("SHAP Waterfall Plot")
    expl = shap.Explanation(values=shap_vals, feature_names=feature_cols, features=X)
    fig = shap.plots.waterfall(expl, show=False)
    st.pyplot(fig)



# =========================================================
#                 PAGE 3 — SHAP GLOBAL
# =========================================================
elif page == "📈 SHAP Explainability":

    st.header("📈 Global SHAP Interpretability")

    st.write("### Bar Plot")
    sample = df[feature_cols].sample(200, random_state=42)
    shap_vals = explainer.shap_values(sample)[1]  # class 1

    fig1 = plt.figure()
    shap.summary_plot(shap_vals, sample, feature_names=feature_cols, plot_type="bar", show=False)
    st.pyplot(fig1)

    st.write("### Beeswarm Plot")
    fig2 = plt.figure()
    shap.summary_plot(shap_vals, sample, feature_names=feature_cols, show=False)
    st.pyplot(fig2)



# =========================================================
#           PAGE 4 — RAG + LLM MOVEMENT EXPLANATION
# =========================================================
elif page == "🧠 RAG Movement Explanation":

    st.header("🧠 Movement Explanation (RAG + LLM)")

    idx = st.number_input("Select row:", min_value=0, max_value=len(df)-1, value=0)
    row = df.iloc[idx]

    shap_vals = shap_for_row(row)
    shap_text = shap_text_summary(row, shap_vals)
    rag_context = retrieve_context("owl movement explanation")

    llm_text = llm_explain(row, shap_text, rag_context)

    st.subheader("Final Explanation (LLM)")
    st.write(llm_text)



# =========================================================
#             PAGE 5 — OWL CHATBOT (RAG)
# =========================================================
elif page == "💬 Owl Chatbot":

    st.header("💬 Owl Chatbot (RAG-enabled)")

    user_query = st.text_input("Ask something about the classifier, owls, or features:")

    if user_query:
        rag_ctx = retrieve_context(user_query)
        prompt = f"""
Background:
{rag_ctx}

Question:
{user_query}

Answer clearly:
"""
        out = generator(prompt, max_new_tokens=150)[0]["generated_text"]
        st.write(out)



# =========================================================
#                 PAGE 6 — DOCUMENTATION
# =========================================================
elif page == "📘 Documentation":

    st.header("📘 Project Documentation")
    st.write("""
    This app combines machine learning, retrieval-augmented generation,
    and explainable AI to classify owl movement behavior.
    """)